version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --reload
    restart: unless-stopped
    
    ports: 
      - 8000:8000
    
